// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPilW_NK5xLUdwH5uo8ArdeFmkGoZefeY',
    appId: '1:358030995038:web:8d41ee6c039ba85acb4ecf',
    messagingSenderId: '358030995038',
    projectId: 'byso-a6393',
    authDomain: 'byso-a6393.firebaseapp.com',
    storageBucket: 'byso-a6393.appspot.com',
    measurementId: 'G-PP31PMC68P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk8Qfr5PXo2d_bfCZ4boiuopdGqjX6mYs',
    appId: '1:358030995038:android:f2b30b4865351b2dcb4ecf',
    messagingSenderId: '358030995038',
    projectId: 'byso-a6393',
    storageBucket: 'byso-a6393.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqE4slPs6SpNfI9Q-xR1Nq5V7srA3Y1ag',
    appId: '1:358030995038:ios:c55dd822bde5b7f8cb4ecf',
    messagingSenderId: '358030995038',
    projectId: 'byso-a6393',
    storageBucket: 'byso-a6393.appspot.com',
    iosBundleId: 'com.byso.byso',
  );
}
